# Generated by Django 5.2.8 on 2025-12-01 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_balance_user_currency_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Order Created'), ('STATUS_CHANGED', 'Status Changed'), ('PROGRESS_UPDATE', 'Progress Updated'), ('CANCELLED', 'Order Cancelled'), ('REFUNDED', 'Order Refunded'), ('NOTE_ADDED', 'Note Added'), ('SUPPLIER_SUBMITTED', 'Submitted to Supplier'), ('ADMIN_UPDATE', 'Admin Update')], max_length=20)),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='users.order')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_actions', to='users.user')),
            ],
            options={
                'verbose_name_plural': 'Order Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id', '-created_at'], name='users_order_order_i_c733a7_idx'), models.Index(fields=['event_type'], name='users_order_event_t_43eb19_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('CUSTOMER', 'Customer Note'), ('ADMIN', 'Admin Note'), ('SYSTEM', 'System Note')], default='CUSTOMER', max_length=10)),
                ('content', models.TextField()),
                ('is_visible_to_customer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id', '-created_at'], name='users_order_order_i_58368a_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='users.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id', '-created_at'], name='users_order_order_i_83fd3e_idx')],
            },
        ),
    ]
