# Generated by Django 5.2.8 on 2025-11-27 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_role',
            new_name='customer_note',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='cancell_enabled',
            new_name='cancel_enabled',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='descriptiom',
            new_name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='average_time',
            field=models.CharField(default='1-2 hours', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='max_quantity',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_per_100',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.supplier'),
        ),
        migrations.AlterField(
            model_name='service',
            name='supplier_price_per_100',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='total_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='users_servi_slug_f1008b_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured', 'status'], name='users_servi_is_feat_61793f_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category_id', 'status'], name='users_servi_categor_0945e2_idx'),
        ),
    ]
