# Generated by Django 5.2.8 on 2025-12-01 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_orderhistory_ordernote_orderstatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5')),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=10)),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='True if user has completed an order for this service')),
                ('helpful_count', models.IntegerField(default=0)),
                ('reported_count', models.IntegerField(default=0)),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(blank=True, help_text='Optional: Link comment to an order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='users.order')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_replies', to='users.user')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_comments', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('OFFENSIVE', 'Offensive Language'), ('FAKE', 'Fake Review'), ('INAPPROPRIATE', 'Inappropriate Content'), ('OTHER', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to='users.user')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.servicecomment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='users.servicecomment')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='users.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_services', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicecomment',
            index=models.Index(fields=['service_id', 'status', '-created_at'], name='users_servi_service_4beeb6_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecomment',
            index=models.Index(fields=['user_id', '-created_at'], name='users_servi_user_id_a75225_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecomment',
            index=models.Index(fields=['status'], name='users_servi_status_2b593d_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicecomment',
            constraint=models.UniqueConstraint(fields=('service_id', 'user_id'), name='unique_user_service_comment'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['comment_id', 'resolved'], name='users_comme_comment_c8e46e_idx'),
        ),
        migrations.AddConstraint(
            model_name='commenthelpful',
            constraint=models.UniqueConstraint(fields=('comment_id', 'user_id'), name='unique_helpful_vote'),
        ),
        migrations.AddIndex(
            model_name='servicefavorite',
            index=models.Index(fields=['user_id', '-created_at'], name='users_servi_user_id_832313_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefavorite',
            index=models.Index(fields=['service_id'], name='users_servi_service_c953fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicefavorite',
            constraint=models.UniqueConstraint(fields=('user_id', 'service_id'), name='unique_user_favorite_service'),
        ),
    ]
