# Generated by Django 5.2.8 on 2025-12-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_servicecomment_commentreport_commenthelpful_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from comments', max_digits=3),
        ),
        migrations.AddField(
            model_name='service',
            name='total_comments',
            field=models.IntegerField(default=0, help_text='Total approved comments'),
        ),
        migrations.AddField(
            model_name='service',
            name='total_favorites',
            field=models.IntegerField(default=0, help_text='Total users who favorited this service'),
        ),
        migrations.AddField(
            model_name='service',
            name='total_ratings',
            field=models.IntegerField(default=0, help_text='Total number of ratings'),
        ),
        migrations.CreateModel(
            name='AdminAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('AWAY', 'Away'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=10)),
                ('max_tickets', models.IntegerField(default=10, help_text='Maximum concurrent tickets')),
                ('current_tickets', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('admin_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('GENERAL', 'General Inquiry'), ('ORDER', 'Order Issue'), ('PAYMENT', 'Payment Issue'), ('ACCOUNT', 'Account Issue'), ('TECHNICAL', 'Technical Issue'), ('REFUND', 'Refund Request'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending Customer Response'), ('IN_PROGRESS', 'In Progress'), ('WAITING', 'Waiting for Admin'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('queue_position', models.IntegerField(default=0, help_text='Position in queue (0 = assigned, >0 = waiting)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, help_text='Customer satisfaction rating (1-5)', null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Admin assigned to this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='users.user')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='users.order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to='users.user')),
                ('assigned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made_from', to='users.user')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_received', to='users.user')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='users.supportticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('USER', 'User Message'), ('ADMIN', 'Admin Reply'), ('SYSTEM', 'System Message'), ('NOTE', 'Internal Note')], default='USER', max_length=10)),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes not visible to customer')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.supportticket')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=15)),
                ('to_status', models.CharField(max_length=15)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='users.supportticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tickettag')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tags', to='users.supportticket')),
            ],
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['ticket_number'], name='users_suppo_ticket__5f69f8_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user_id', 'status'], name='users_suppo_user_id_497297_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status'], name='users_suppo_assigne_65dc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='users_suppo_status_8b3d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['queue_position', 'created_at'], name='users_suppo_queue_p_bd0453_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket_id', 'created_at'], name='users_ticke_ticket__ba2019_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tickettagrelation',
            unique_together={('ticket_id', 'tag_id')},
        ),
    ]
