# Generated by Django 5.2.8 on 2025-12-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tickettag_service_average_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='users_servi_categor_ebfeac_idx',
            old_name='users_servi_categor_0945e2_idx',
        ),
    ]
