# Generated by Django 5.2.8 on 2025-12-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_category_id_service_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='test',
        ),
    ]
