# Generated by Django 5.2.8 on 2025-12-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_payment_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='service_id',
            new_name='service',
        ),
    ]
